LABELS = [
    "person",
    "organization",
    "location",
    "country",
    "city",
    "state",
    "date",
    "time",
    "weapon",
    "drone",
    "missile",
    "aircraft",
    "fighter jet",
    "tank",
    "ship",
    "vehicle",
    "airbase",
    "military base",
    "border",
    "terrorist organization",
]