apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis.yaml
  - api-deployment.yaml
  - research-api-deployment.yaml
  - frontend-deployment.yaml
secretGenerator:
  - name: trinetra-secrets
    literals:
      - openai-api-key=
    options:
      disableNameSuffixHash: true
